### PR TITLE
5222 handle authn request

### PR DESCRIPTION
**Pull request by richardTowers**
This PR comprises all the work needed for the bridge to receive and validate AuthnRequests from Verify.

Firstly, it needs to request Metadata from Verify, for which it uses the `MetadataResolver` from  `saml-metadata-bindings`. There's a dropwizard healthcheck that checks this is working.

Secondly, it needs an endpoint which can receive the form POST which will contain the SAMLRequest and the RelayState.

Dependencies have been wired manually (rather than using an IoC framework a la guice) in the `VerifyEidasBridgeFactory` - this factory may need splitting up later when we have more things to wire up.

We've made the bridge start on port 50400, so that it doesn't clash with any of the other verify microservices when running on localhost.

There are AppRule tests which exercise the whole app to check that it requests Metadata and that it can validate signatures on AuthnRequests. These use WireMock to stub out requests for Metadata.

There are also simple unit tests for the AuthnRequestHandler.

Finally there's an acceptance test (in a different repo - https://github.com/alphagov/eidas-reference-acceptance-tests/blob/master/spec/bridge-compliance/bridge_compliance_tool_spec.rb) which uses the compliance tool to post an AuthnRequest to the bridge and expects a 200 OK.

### CODE REVIEW

**Comment by niyioyelade** [comment]
Hello Rich,
I am still receiving email of pull request and commits, you may want to remove me from the group/project. I don't actually mind either way though.
Best regards,
'Niyi 

    On Monday, 14 November 2016, 15:14, Richard Towers <notifications@github.com> wrote:
 

 
You can view, comment on, or merge this pull request online at:
  https://github.com/alphagov/verify-eidas-bridge/pull/1
Commit Summary
   
   - 5222: Tests and (non-working) code for requesting Metadata
   - 5222: Configure test to use truststore and metadata
   - 5222: Use a dynamic port for webmock
   - 5222: Use correct metadata from saml-metadata-bindings
   - 5222: Move metadataResolver construction into a factory
   - 5222: Create an App Rule Test to Generate and send an Authn Request to the Bridge
   - 5222: remove dependency on hub-saml and validate AuthRequest
   - 5222: Failing test for validation of AuthnRequest
   - 5222: Use wireMock for providing Metadata in AuthnRequest test
   - 5222: Use correct keys for authn request
   - 5222: Tidy up gradle file slightly
   - 5222: Refactor handling of AuthnRequests into a helper class
   - 5222: Add unit test for AuthnRequestHandler
   - 5222: Correct resource to take a form post, rather than an XML blob
   - 5222: Remove some unused imports
   - 5222: Add a truststore to trust the compliance tools metadata
   - 5222: Fix config to point at the compliance tool's metadata
   - 5222: Add a script for initializing the compliance tool
   - 5222: Change default port to 50400
   - 5222: Log signature validation errors
   - 5222: Rename test truststore to make it obvious it's for tests
   - 5222: Tidy build.gradle

File Changes
   
   -  M build.gradle (22) 
   -  A initialize-compliance-tool.rb (21) 
   -  M src/dist/eidasbridge.yml (23) 
   -  M src/main/java/uk/gov/ida/eidas/bridge/BridgeApplication.java (19) 
   -  M src/main/java/uk/gov/ida/eidas/bridge/BridgeConfiguration.java (12) 
   -  A src/main/java/uk/gov/ida/eidas/bridge/factories/VerifyEidasBridgeFactory.java (93) 
   -  A src/main/java/uk/gov/ida/eidas/bridge/helpers/AuthnRequestHandler.java (40) 
   -  D src/main/java/uk/gov/ida/eidas/bridge/resources/EidasBridgeResource.java (17) 
   -  A src/main/java/uk/gov/ida/eidas/bridge/resources/VerifyAuthnRequestResource.java (42) 
   -  A src/main/resources/metadata_truststore.ts (0) 
   -  A src/test/java/uk.gov.ida.eidas.bridge/apprule/BridgeApplicationIntegrationTest.java (57) 
   -  A src/test/java/uk.gov.ida.eidas.bridge/apprule/SendAuthnRequestToBridgeIntegrationTest.java (99) 
   -  A src/test/java/uk.gov.ida.eidas.bridge/helpers/AuthnRequestHandlerTest.java (60) 
   -  A src/test/java/uk.gov.ida.eidas.bridge/rules/MetadataRule.java (37) 
   -  A src/test/java/uk.gov.ida.eidas.bridge/testhelpers/AuthnRequestBuilder.java (48) 
   -  A src/test/java/uk.gov.ida.eidas.bridge/testhelpers/IdaAuthnRequestFromHubToAuthnRequestTransformer.java (49) 
   -  A src/test/java/uk.gov.ida.eidas.bridge/testhelpers/IdaAuthnRequestToAuthnRequestTransformer.java (42) 
   -  A src/test/resources/eidasbridge.yml (33) 
   -  A src/test/resources/test_metadata_truststore.ts (0) 

Patch Links:
   
   - https://github.com/alphagov/verify-eidas-bridge/pull/1.patch
   - https://github.com/alphagov/verify-eidas-bridge/pull/1.diff

**Comment by richardTowers** [comment]
Thanks Niyi. I'll raise a story to get you removed from everything. @chrisholmes will need to do the github foo as I'm not an admin. You may still get some notifications if we rebase commits that your name is tagged against though (hopefully not too many).

**Comment by niyioyelade** [comment]
That's absolutely fine Richard.
Cheers.
'Niyi 

    On Monday, 14 November 2016, 16:09, Richard Towers <notifications@github.com> wrote:
 

 Thanks Niyi. I'll raise a story to get you removed from everything. @chrisholmes will need to do the github foo as I'm not an admin. You may still get some notifications if we rebase commits that your name is tagged against though (hopefully not too many).—

**Comment by richardTowers** [comment]
Going to go ahead and merge this.

**Pull request merged**
